AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AccessModifierDeclarations:
  AllowModifiersOnSymbols: false
Style/DefWithParentheses:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  Enabled: true
  IgnoreMacros: true
  EnforcedStyle: require_parentheses
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
